# Generated by Django 3.1.1 on 2020-10-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sem',
            field=models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'fourth'), ('5', 'fifth'), ('6', 'sixth'), ('7', 'seventh'), ('8', 'eigth')], default='first', max_length=1),
        ),
    ]
